[package]
name = "msix"
version = "0.4.0"
edition = "2021"
description = "Library for creating and signing msix packages."
repository = "https://github.com/rust-mobile/xbuild"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.68"
base64 = "0.20.0"
byteorder = "1.4.3"
mime_guess = "2.0.4"
quick-xml = { version = "0.26.0", features = ["serialize"] }
rasn.workspace = true
rasn-cms.workspace = true
rasn-pkix.workspace = true
serde = { version = "1.0.151", features = ["derive"] }
sha2 = "0.10.6"
xcommon = { version = "0.3.0", path = "../xcommon" }
zip = { version = "0.6.3", default-features = false }

[dev-dependencies]
der-parser = "8.1.0"
rsa = "0.7.2"
