[package]
name = "appimage"
version = "0.3.0"
edition = "2021"
description = "Library for creating and signing appimages."
repository = "https://github.com/cloudpeers/x"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.53"
xcommon = { version = "0.2.0", path = "../xcommon" }
