[package]
name = "xcommon"
version = "0.2.1"
edition = "2021"
description = "Utilities for x."
repository = "https://github.com/cloudpeers/x"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.53"
byteorder = "1.4.3"
image = { version = "0.24.0", default-features = false, features = ["png"] }
pem = "1.0.2"
rasn = "0.5.0"
rasn-pkix = "0.5.0"
rsa = "0.6.0"
sha2 = "0.10.1"
zip = { version = "0.6.0", default-features = false, features = ["deflate"] }
